# Generated by Django 5.2.12 on 2026-04-06 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSTReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('GSTR-1', 'GSTR-1'), ('GSTR-3B', 'GSTR-3B'), ('GSTR-2A', 'GSTR-2A'), ('GSTR-2B', 'GSTR-2B'), ('GSTR-9', 'GSTR-9'), ('GSTR-9C', 'GSTR-9C')], max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('due_date', models.DateField()),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Pending', 'Pending'), ('In Review', 'In Review'), ('Filed', 'Filed'), ('Overdue', 'Overdue'), ('Revised', 'Revised')], default='Upcoming', max_length=20)),
                ('next_step', models.CharField(blank=True, choices=[('Prepare in GSTR-1', 'Prepare in GSTR-1'), ('Prepare in GSTR-3B', 'Prepare in GSTR-3B'), ('Download ack', 'Download ack'), ('Download challan', 'Download challan'), ('File Now', 'File Now'), ('Pay Late Fee', 'Pay Late Fee'), ('Under Review', 'Under Review'), ('Revised Filing', 'Revised Filing')], max_length=50, null=True)),
                ('arn_ack_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ack_file', models.FileField(blank=True, null=True, upload_to='gst_ack/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('return_type', 'period')},
            },
        ),
        migrations.CreateModel(
            name='GSTReturnAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('gst_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='returns_calendar.gstreturn')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
