# Generated by Django 5.2.12 on 2026-04-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSTRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Delhi', 'Delhi'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Ladakh', 'Ladakh'), ('Puducherry', 'Puducherry')], max_length=100)),
                ('registration_type', models.CharField(choices=[('Regular', 'Regular'), ('Composition', 'Composition'), ('SEZ', 'SEZ'), ('Casual', 'Casual'), ('Non-Resident', 'Non-Resident'), ('ISD', 'ISD'), ('UIN', 'UIN')], default='Regular', max_length=50)),
                ('effective_date', models.DateField()),
                ('return_frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually')], default='Monthly', max_length=20)),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='Default GST rate in percentage', max_digits=5)),
                ('rounding_rule', models.CharField(choices=[('Nearest', 'Nearest'), ('Round Up', 'Round Up'), ('Round Down', 'Round Down')], default='Nearest', max_length=20)),
                ('place_of_supply_rule', models.CharField(choices=[('Ship To', 'Ship To'), ('Bill To', 'Bill To'), ('Supplier Location', 'Supplier Location')], default='Ship To', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Inactive', 'Inactive')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GST Registration',
                'verbose_name_plural': 'GST Registrations',
                'db_table': 'gst_registration',
                'ordering': ['-created_at'],
            },
        ),
    ]
