# Generated by Django 5.2.12 on 2026-03-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_category_code_category_created_at_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gateway_status', models.CharField(choices=[('Initiated', 'Initiated'), ('Processing', 'Processing'), ('Cleared', 'Cleared'), ('Failed', 'Failed'), ('Reattempt', 'Reattempt')], default='Initiated', max_length=20)),
                ('allocation_status', models.CharField(choices=[('Unallocated', 'Unallocated'), ('Partially Allocated', 'Partially Allocated'), ('Allocated', 'Allocated'), ('Overpayment', 'Overpayment')], default='Unallocated', max_length=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Applied', 'Applied'), ('Unapplied', 'Unapplied'), ('Failed', 'Failed'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled')], default='Unapplied', max_length=20)),
                ('invoice_allocation', models.TextField(blank=True)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
            ],
        ),
    ]
