# Generated by Django 6.0.2 on 2026-03-24 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateField()),
                ('expected_dispatch_date', models.DateField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('salesperson', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('dispatched_items', models.PositiveIntegerField(default=0)),
                ('dispatch_status', models.CharField(choices=[('open', 'Open'), ('partially_dispatched', 'Partially Dispatched'), ('dispatched', 'Dispatched')], default='open', max_length=30)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('dispatched_quantity', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_orders.salesorder')),
            ],
            options={
                'db_table': 'sales_order_items',
            },
        ),
    ]
