# Generated by Django 5.2.12 on 2026-04-06 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('invoice_date', models.DateField()),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('place_of_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('irn', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('irn_status', models.CharField(choices=[('Pending', 'Pending'), ('Generated', 'Generated'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('irn_generated_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_eligible', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-Invoice',
                'verbose_name_plural': 'E-Invoices',
                'db_table': 'e_invoice',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='IRNAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Generated', 'Generated'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed'), ('Retried', 'Retried')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('e_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='e_invoice.einvoice')),
            ],
            options={
                'verbose_name': 'IRN Audit Log',
                'verbose_name_plural': 'IRN Audit Logs',
                'db_table': 'irn_audit_log',
                'ordering': ['-performed_at'],
            },
        ),
    ]
