# Generated by Django 5.2.12 on 2026-04-06 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(max_length=100, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('challan_date', models.DateField()),
                ('vehicle_number', models.CharField(max_length=20)),
                ('transporter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('from_place', models.CharField(blank=True, max_length=255, null=True)),
                ('to_place', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ewaybill_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ewaybill_status', models.CharField(choices=[('Pending', 'Pending'), ('Generated', 'Generated'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('valid_upto', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-challan_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EWayBillAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('e_way_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ewaybill.ewaybill')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
