# Generated by Django 5.2.12 on 2026-04-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('travel_transport', 'Travel & Transport'), ('office_supplies', 'Office Supplies'), ('marketing_ads', 'Marketing & Ads'), ('it_software', 'IT & Software'), ('rent', 'Rent'), ('legal', 'Legal')], max_length=50)),
                ('date', models.DateField()),
                ('vendor_payee', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('paid_via', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('upi', 'UPI'), ('cash', 'Cash')], max_length=30)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
