# Generated by Django 5.2.12 on 2026-04-24 16:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('expected_receipt_date', models.DateField(blank=True, null=True)),
                ('vendor_name', models.CharField(max_length=150)),
                ('vendor_company', models.CharField(blank=True, max_length=180)),
                ('po_status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='open', max_length=30)),
                ('debit_note_status', models.CharField(choices=[('none', 'None'), ('draft', 'Draft'), ('non_draft', 'Non-Draft')], default='non_draft', max_length=20)),
                ('received_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('qty_ordered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('qty_returned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gross_purchases', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('returns_adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_purchases', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_report.purchaseorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
