# Generated by Django 5.2.12 on 2026-04-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('rent_utilities', 'Rent & Utilities'), ('it_software', 'IT & Software'), ('legal_compliance', 'Legal & Compliance'), ('travel_transport', 'Travel & Transport'), ('office_supplies', 'Office Supplies'), ('marketing_ads', 'Marketing & Ads')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('next_run', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('due_soon', 'Due Soon')], default='active', max_length=20)),
                ('vendor_payee', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('auto_post_ledger', models.BooleanField(default=True)),
                ('notify_before_run', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
    ]
