# Generated by Django 5.2.12 on 2026-04-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('qty_sold', models.PositiveIntegerField(default=1)),
                ('taxable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('returns', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('outstanding', 'Outstanding'), ('overdue', 'Overdue')], default='outstanding', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
