# Generated by Django 5.2.12 on 2026-03-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('voucher_type', models.CharField(choices=[('Journal', 'Journal'), ('Receipt', 'Receipt'), ('Payment', 'Payment'), ('Contra', 'Contra'), ('Sales Invoice', 'Sales Invoice'), ('Purchase Invoice', 'Purchase Invoice')], default='Journal', max_length=30)),
                ('transaction_date', models.DateField()),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_account', models.CharField(max_length=255)),
                ('credit_account', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gst_tax_rate', models.CharField(choices=[('No tax', 'No Tax'), ('GST 5%', 'GST 5%'), ('GST 12%', 'GST 12%'), ('GST 18%', 'GST 18%'), ('GST 28%', 'GST 28%')], default='No tax', max_length=20)),
                ('narration', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('source', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual')], default='Manual', max_length=10)),
                ('is_tax_entry', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
