# Generated by Django 5.2.12 on 2026-04-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSTLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_type', models.CharField(choices=[('Input', 'Input'), ('Output', 'Output')], max_length=10)),
                ('voucher_type', models.CharField(choices=[('Expense', 'Expense'), ('Sales Invoice', 'Sales Invoice'), ('Purchase Invoice', 'Purchase Invoice'), ('Credit Note', 'Credit Note'), ('Debit Note', 'Debit Note'), ('Journal', 'Journal')], max_length=50)),
                ('ref', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('party_name', models.CharField(blank=True, max_length=255, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('is_posted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GST Ledger Entry',
                'verbose_name_plural': 'GST Ledger Entries',
                'db_table': 'gst_ledger',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
