# Generated by Django 6.0.2 on 2026-03-12 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('adjustment_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('adjustment_type', models.CharField(choices=[('Add', 'Add'), ('Remove', 'Remove'), ('Damaged', 'Damaged'), ('Expired', 'Expired'), ('Return', 'Return'), ('Transfer', 'Transfer')], max_length=20)),
                ('reason', models.CharField(choices=[('Manual Count', 'Manual Count'), ('Damaged Goods', 'Damaged Goods'), ('Expired Stock', 'Expired Stock'), ('Supplier Return', 'Supplier Return'), ('Customer Return', 'Customer Return'), ('Internal Use', 'Internal Use'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('warehouse', models.CharField(choices=[('Main Store', 'Main Store'), ('Warehouse A', 'Warehouse A'), ('Warehouse B', 'Warehouse B')], default='Main Store', max_length=100)),
                ('bin_location', models.CharField(blank=True, max_length=100)),
                ('quantity_before', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjusted_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_after', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjustment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('quantity_before', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjusted_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_after', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('bin_location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock_adjustment.stockadjustment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
    ]
