# Generated by Django 6.0.2 on 2026-03-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_adjustment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='direction',
            field=models.CharField(choices=[('Add', 'Add'), ('Reduce', 'Reduce')], default='Add', max_length=10),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
