# Generated by Django 6.0.2 on 2026-03-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_adjustment', '0002_stockadjustment_direction_stockadjustment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_number',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('Add', 'Add'), ('Remove', 'Remove'), ('Damaged', 'Damaged'), ('Manual Correction', 'Manual Correction'), ('Expired', 'Expired'), ('Return', 'Return'), ('Transfer', 'Transfer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Pending Review', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
    ]
