# Generated by Django 5.2.12 on 2026-04-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HsnSac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('HSN', 'HSN (Goods)'), ('SAC', 'SAC (Services)')], max_length=10)),
                ('gst_rate', models.DecimalField(choices=[(0, '0%'), (0.1, '0.1%'), (0.25, '0.25%'), (1, '1%'), (1.5, '1.5%'), (3, '3%'), (5, '5%'), (6, '6%'), (7.5, '7.5%'), (12, '12%'), (18, '18%'), (28, '28%')], decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Inactive', 'Inactive')], default='Draft', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField()),
                ('map_to', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HSN/SAC Code',
                'verbose_name_plural': 'HSN/SAC Codes',
                'db_table': 'hsn_sac',
                'ordering': ['-created_at'],
            },
        ),
    ]
