# Generated by Django 6.0.2 on 2026-03-10 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('batch_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('received_on', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('available_units', models.PositiveIntegerField(default=0)),
                ('reserved_units', models.PositiveIntegerField(default=0)),
                ('damaged_units', models.PositiveIntegerField(default=0)),
                ('bin_location', models.CharField(blank=True, max_length=100)),
                ('batch_status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Released', 'Released'), ('Quarantine', 'Quarantine'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=20)),
                ('qa_status', models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('bin_location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_batch.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
    ]
