# Generated by Django 5.2.12 on 2026-03-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Net Profit', 'Net Profit')], max_length=50)),
                ('account', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('branch', models.CharField(default='All Branches', max_length=100)),
                ('cost_center', models.CharField(default='All Centers', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ledger_pl',
                'ordering': ['category', 'account'],
            },
        ),
        migrations.CreateModel(
            name='PLBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Revenue (Gross)', 'Revenue (Gross)'), ('Returns/Discounts', 'Returns/Discounts'), ('Revenue (Net)', 'Revenue (Net)'), ('COGS', 'COGS'), ('Gross Profit', 'Gross Profit'), ('Operating Expenses', 'Operating Expenses'), ('Net Profit', 'Net Profit')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pl_breakdown',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProfitLossStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('branch', models.CharField(default='All Branches', max_length=100)),
                ('cost_center', models.CharField(default='All Centers', max_length=100)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cogs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profit_loss_statements',
                'ordering': ['-period_from'],
            },
        ),
    ]
