# Generated by Django 5.2.12 on 2026-04-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITCReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_ref', models.CharField(max_length=100, unique=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_gstin', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('match_status', models.CharField(choices=[('Matched', 'Matched'), ('Pending', 'Pending'), ('Mismatch', 'Mismatch'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('mismatch_reason', models.CharField(blank=True, choices=[('Invoice Not Reflected', 'Invoice Not Reflected'), ('GSTIN Mismatch', 'GSTIN Mismatch'), ('Tax Amount Mismatch', 'Tax Amount Mismatch'), ('Invoice Date Mismatch', 'Invoice Date Mismatch'), ('Duplicate Entry', 'Duplicate Entry'), ('Cancelled Invoice', 'Cancelled Invoice'), ('Other', 'Other')], max_length=50, null=True)),
                ('eligible', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Partial', 'Partial')], max_length=10, null=True)),
                ('eligible_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice_document', models.FileField(blank=True, null=True, upload_to='itc_invoices/')),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ITC Reconciliation',
                'verbose_name_plural': 'ITC Reconciliations',
                'db_table': 'itc_reconciliation',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
