# Generated by Django 5.2.12 on 2026-04-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSTTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Output', 'Output'), ('Input', 'Input')], max_length=10)),
                ('transaction_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('state_code', models.CharField(blank=True, max_length=5, null=True)),
                ('party_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Cancelled', 'Cancelled'), ('Returns', 'Returns')], default='Paid', max_length=20)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_rate', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')], default=18)),
                ('is_reverse_charge', models.BooleanField(default=False)),
                ('is_nil_exempt', models.BooleanField(default=False)),
                ('is_non_gst', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
